apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3proxy
  template:
    metadata:
      labels:
        app: s3proxy
    spec:
      containers:
      - name: s3proxy
        image: andrewgaul/s3proxy:latest
        ports:
          - containerPort: 80
        env:
          - name: S3PROXY_AUTHORIZATION
            value: "none"
          - name: JCLOUDS_PROVIDER
            value: "azureblob"
          - name: JCLOUDS_ENDPOINT
            value: "https://<azure storage acc>.blob.core.windows.net"
          - name: JCLOUDS_IDENTITY
            value: "<azure storage a/c>"
          - name: JCLOUDS_CREDENTIAL
            value: "<Azure storage access key>"
          - name: JCLOUDS_AZYREBLOB_AUTH
            value: "azureKey"
          - name: LOG_LEVEL
            value: "debug"
          
